version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: asspass
      MYSQL_DATABASE: development
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh wait-for-db.sh db asspass 
  ldap:
    container_name: openldap
    image: osixia/openldap:1.1.10
    environment:
      LDAP_DOMAIN: chalmers.it
      LDAP_TLS: "false"
    volumes:
      - ./misc/ldap:/var/lib/ldap
      - ./misc/slapd.d:/etc/ldap/slapd.d
    ports:
      - "389"
